landmark_codes_en = {
    'nose':0,
    'left_eye_inner':1,
    'left_eye' : 2,
    'left_eye_outer' : 3,
    'right_eye_inner' : 4,
    'right_eye' : 5,
    'right_eye_outer' : 6,
    'left_ear' : 7,
    'right_ear' : 8,
    'mouth_left' : 9,
    'mouth_right': 10,
    'left_shoulder': 11,
    'right_shoulder': 12,
    'left_elbow': 13,
    'right_elbow': 14,
    'left_wrist': 15,
    'right_wrist': 16,
    'left_pinky': 17,
    'right_pinky': 18,
    'left_index': 19,
    'right_index': 20,
    'left_thumb': 21,
    'right_thumb': 22,
    'left_hip': 23,
    'right_hip': 24,
    'left_knee': 25,
    'right_knee': 26,
    'left_ankle': 27,
    'right_ankle': 28,
    'left_heel': 29,
    'right_heel': 30,
    'left_foot_index': 31,
    'right_foot_index': 32
}

landmark_codes_pt_br = {
    'nariz':0,
    'interior_olho_esquerdo':1,
    'olho_esquerdo' : 2,
    'exterior_olho_esquerdo' : 3,
    'interior_olho_direito' : 4,
    'olho_direito' : 5,
    'exterior_olho_direito' : 6,
    'orelha_esquerda' : 7,
    'orelha_direita' : 8,
    'boca_esquerda' : 9,
    'boca_direita': 10,
    'ombro_esquerdo': 11,
    'ombro_direito': 12,
    'cotovelo_esquerdo': 13,
    'cotovelo_direito': 14,
    'pulso_esquerdo': 15,
    'pulso_direito': 16,
    'mindinho_esquerdo': 17,
    'mindinho_direito': 18,
    'indicador_esquerdo': 19,
    'indicador_direito': 20,
    'polegar_esquerdo': 21,
    'polegar_direito': 22,
    'quadril_esquerdo': 23,
    'quadril_direito': 24,
    'joelho_esquerdo': 25,
    'joelho_direito': 26,
    'tornozelo_esquerdo': 27,
    'tornozelo_direito': 28,
    'calcanhar_esquerdo': 29,
    'calcanhar_direito': 30,
    'indicador_pe_esquerdo': 31,
    'indicador_pe_direito': 32
}

